### PR TITLE
Allow nil values for datetime

### PR DESCRIPTION
**Pull request by lucaguindani**
@christiankaiser can you please check that the changes suit you ?

It will modify the output of the DateTime field, but seems to me it's the most flexible way to do things for the catalog editors.

I had to modify some tests for this, can you check if in your opinion it's not breaking things (value_as_int function) ?

Thanks.

### CODE REVIEW

**Comment by christiankaiser** [comment]
Thanks for the PR. I don't quite understand why we cannot use anymore directly the datetime format option (field.format) and then use the locale version as formatting string. The advantage of the old version was clearly to allow for language-specific adaptations in the datetime format. Currently, the German version of the date format is wrong, the dot after the day is mandatory and cannot be removed. The English version is somewhat more flexible, so removing the comma there is still ok.

I think this PR is overcomplicating things, or at least I don't see the benefits of a good amount of it. Allowing nil values for the datetime field could be done more easily I think.

**Comment by lucaguindani** [comment]
@christiankaiser thanks for your feedback.

> I don't quite understand why we cannot use anymore directly the datetime format option (field.format) and then use the locale version as formatting string.

Because if we allow nil values you won't have only the following possibilities anymore.

```
Y: "%Y"
YM: "%B %Y"
YMD: "%d %B, %Y"
YMDh: "%d %B, %Y %Hh"
YMDhm: "%d %B, %Y %H:%M"
YMDhms: "%d %B, %Y %H:%M:%S"
```

I can be YMhms or Yhm or any combination for that matter. So I don't see how it's possible to keep the per-local format. Any idea ?

**Comment by christiankaiser** [comment]
Aha I see what you want to do. I was thinking to give just two possibilities:
- set the whole datetime field to nil (no value at all)
- or fill correctly out the available fields

But allowing nil values for each individual value is a different matter. It can be done additionally to nulling the whole field IMO. But it raises the question which combinations make actually sense. I do not think it makes sense to have for example a date with only the day and the year but without month. This considerably limits the possibilities. Maybe we need anyway to make a list with the acceptable combinations. After some thinking, for me only the following combinations actually make sense:

`%w(Y M h YM MD hm YMD hms MDh YMDh MDhm YMDhm MDhms YMDhms)`

Do you see any other reasonable use cases for other combinations?

**Comment by lucaguindani** [comment]
it was "Date of represented event" I think

**Comment by christiankaiser** [comment]
In these two fields, we can indeed have either the year, or the precise date, so Y or YMD. In this case the field format should be YMD, with the possibility to leave either leave D nil, or M+D nil. For formatting, we would have at maximum the 14 possibility listed above.

For getting the formatting string, we could e.g. do something like this:
```
d = {Y: 2018, M: 4, D: 13, h: 15}
format = "YMDhm"
format_str = format.split('').select{ |v| !d[v.to_sym].nil? }.join
```

We still would need to validate the formatting string, so if we have some invalid string like the YDh below, we could change it by removing the "smaller" values until the string becomes valid:

```
def validate_datetime_format_string(dtstr)
  allowed_formats = %w(Y M h YM MD hm YMD hms MDh YMDh MDhm YMDhm MDhms YMDhms)
  s = dtstr
  loop do
    break if allowed_formats.include?(s) || s.length == 0
    s = s[0...-1]
  end
  s
end
```

with an example:
```
d = {Y: 2018, M: nil, D: 13, h: 15}
format = "YMDhm"
format_str = format.split('').select{ |v| !d[v.to_sym].nil? }.join
validate_datetime_format_string(format_str)
```

But we need to bring this logic also to the editing interface to allow only for valid formats.

**Comment by christiankaiser** [comment]
Yes exactly. I think it does make more sense than allowing any combination as rendering arbitrary combinations can be really tricky.

**Comment by lucaguindani** [comment]
Finally had time to work on this feature, I let you check the changes.

**Pull request merged**
