### PR TITLE
Migration to Rails 5.2

### PR DESCRIPTION
**Pull request by jurtn**

### CODE REVIEW

**Comment by jurtn** [comment]
- There was indeed an issue with the xref test. I have temporarily removed the test as the xref anyway needs a fix for performance.

- The catalog dump test has been somehow triggered twice, yielding an error message that the catalog already exists (the test first loads a catalog from a directory and dumps it again). I do not yet fully understand what is going on there but I would be surprised if it is anything related to Rails 5. But I did also see that there is anyway a problem with the catalog load task for this dump. It yields an error during import with some fields that are not found. I think first the catalog load issue needs some investigation and the test can be fixed afterwards.

- The arcgisonline layer did yield some error (operation not authorized or something like this). The openstreetmap layer from the GeoEditor did not have this problem, so I did switch them.

- For jQuery and the other libraries in the base.html.erb layout. Before, jQuery and some other libraries were loaded twice, through the Rails asset pipeline and through the React components. This did bring up some random errors depending on when which library has been loaded. We need to make sure these libraries are loaded only once, before the other code. One way of doing this is this kind-of-ugly hack. It has the advantage to use a CDN, so loading should be pretty fast and the browser can do the caching job better than with the Rails assets. The drawback is that in production the number of HTTP requests is a bit higher. However, I don't think this will have any negative impact on performance at the end.

**Comment by christiankaiser** [comment]
Two other things I have found:

- file / image upload seems not to be working
- overall test coverage dropped to around 80%

**Comment by jurtn** [comment]
I think it is an improvement to not to have to load some JS libraries in the public version of the app, and to include them only in the catalog admin.

But I *really* don't like that there is this jquery-fileupload library directly in our code base. And I am still preferring including the JS libraries in the assets pipeline wherever possible.

Part of the problem for the jQuery loading issues, and preventing loading two version of jQuery, is probably the async tag for the assets JS. We need to make sure some of the libraries are loaded before the others.

I'd rather like to see a solution with more than 1 JS assets file. One for the base libraries that is loaded without the async tag, one for the additional ones, and finally one for the catalog admin where we don't necessarily need the async too. Maybe application.js, application-core.js, catalog-admin.js and catalog-admin-core.js ?

**Comment by jurtn** [comment]
I think it is an improvement to not to have to load some JS libraries in the public version of the app, and to include them only in the catalog admin.

But I really don't like that there is this jquery-fileupload library directly in our code base. And I am still preferring including the JS libraries in the assets pipeline wherever possible.

Part of the problem for the jQuery loading issues, and preventing loading two version of jQuery, is probably the async tag for the assets JS. We need to make sure some of the libraries are loaded before the others.

I'd rather like to see a solution with more than 1 JS assets file. One for the base libraries that is loaded without the async tag, one for the additional ones, and finally one for the catalog admin where we don't necessarily need the async too. Maybe application.js, application-core.js, catalog-admin.js and catalog-admin-core.js ?

With this solution, we would cut down the loading size for the public version.

For the test coverage, there is some more code due to the migration to Rails 5. There are also some dropped tests. And there also might be some differences in coverage evaluation. Test coverage needs to be increased, there are some blind spots in the app now. I think this needs to be a separate task.

**Pull request merged**
