### PR TITLE
Geometry editing by direct coordinate input

### PR DESCRIPTION
**Pull request by christiankaiser**
Updated React component allowing editing of point geometries also by coordinates. Does not Leaflet Draw or react-leaflet, but Leaflet directly, due to requirements for fine control of behaviour.

### CODE REVIEW

**Comment by lucaguindani** [comment]
Hello @christiankaiser, I got some console errors in data editing mode when there is a geometry field.

cons_errors_catima_geometry

**Comment by lucaguindani** [comment]
@christiankaiser 
No more errors since your last commit.

Just to let you know I also have a console error with an empty map when no coordinates are found for an item type. It's happening when viewing a page with a map container.

capture d ecran 2018-07-02 a 14 11 11
capture d ecran 2018-07-02 a 14 11 25

I also have a never ending "loading..." string when clicking on a map point (map container).

capture d ecran 2018-07-02 a 14 09 30

**Comment by christiankaiser** [comment]
@lucaguindani I did not remember that the map container was also in the commit. Of course there are problems not yet fixed. I'll update the PR accordingly.

**Comment by lucaguindani** [comment]
@christiankaiser tried the pr with you last commits, and I have a couple of remarks.

I always get an error when loading an item in a map container popup. Looks like the issue comes from an hard-coded catalog slug.

https://github.com/catima/catima/blob/4a10e7a9c861e52ecd16c669fa42cb6fb6fbcbfb/app/views/containers/_map.html.erb#L43

Also I think the "bounds" feature would be better off as a Geometry field attribute rather than a catalog-wide property. For catalogs without geometry fields it's only creating confusion I think. Just a thought ;)

**Comment by lucaguindani** [comment]
@christiankaiser since you're already modifying the geometry field. A Catima user told us that the map is not the same in edition and in the public view.

https://catima.unil.ch/atlastopvaud/fr/admin/toponymes/3497-addos/edit
https://catima.unil.ch/atlastopvaud/fr/toponymes/3497-addos

Is it possible to have the topographic version in both views ?

**Comment by christiankaiser** [comment]
@lucaguindani I would like to rather go for the possibility to define the base layers catalog-wide, with the option to customize further for Map containers. I'll do this in a separate PR. In the meantime, I create an issue with this comment.

**Comment by christiankaiser** [comment]
Just now the bounds are a catalog option. Maybe at the level of the geometry field makes sense. And yes, I still need to make something usable for defining the bounds... Just now you need to type in something like `{"xmin": 6.5, "ymin": 45.3, "xmax": 8.5, "ymax": 46.5}` which is definitely very user-friendly...

**Comment by lucaguindani** [comment]
> which is definitely **not** very user-friendly

you mean ;)

Ok, no problem, just tell me when you need me to test something (I won't be available next week).

**Comment by lucaguindani** [comment]
@christiankaiser I just saw an other issue with map containers.

In a map container, the popup links are not considering the current locale. The json response always gives you an url with the catalog primary language and not the current language.

https://github.com/catima/catima/blob/a6aedc64232dfcd2a75bfefe6d155db857dbdc6e/app/views/containers/_map.html.erb#L52

**Pull request merged**
