### PR TITLE
Update line container style

### PR DESCRIPTION
**Pull request by abstracts33d**
image
image
image

### CODE REVIEW

**Review by skyporter — APPROVED** [review]

**Comment by lucaguindani** [comment]
- [ ] [line-items-disposition](https://github.com/catima/catima/assets/1675064/31ef561d-28ad-4eac-a60c-85d892f8a217) items under the same hierarchy should be on the same side
- [ ] [line-items-margin](https://github.com/catima/catima/assets/1675064/ca633b24-600a-4311-9147-e9d16ebe8b11) Reduce the bottom margin of the items
- [ ] [line-label-overlap](https://github.com/catima/catima/assets/1675064/f4308577-96ce-4c20-8c01-d18d00720e87) Avoid overlap with long labels

@abstracts33d

**Comment by skyporter** [comment]
> [ ] [line-label-overlap](https://github.com/catima/catima/assets/1675064/0194f6e5-75f0-48ca-9d91-374d1e705f5e) Avoid overlap with long labels

About this request, it's not possible to have multiple lines since we move up the content of items by a fixed number of pixels. But it's possible to truncate the text (and add a title) to keep it on one line and prevent overlap with content.

**Comment by lucaguindani** [comment]
> > [ ] [line-label-overlap](https://github.com/catima/catima/assets/1675064/0194f6e5-75f0-48ca-9d91-374d1e705f5e) Avoid overlap with long labels
> 
> @lucaguindani About this request, it's not possible to have multiple lines since we move up the content of items by a fixed number of pixels. But it's possible to truncate the text (and add a title) to keep it on one line and prevent overlap with content.

@skyporter 

I don't think it's an issue. If you add a max-width (~310px) to the .line__group__title it should work. Maybe it should have different values depending on the screen size.

**Comment by skyporter** [comment]
> I don't think it's an issue. If you add a max-width (~310px) to the .line__group__title it should work. Maybe it should have different values depending on the screen size.

there will be this kind of problem, the "sub" content below will be hidden.

screenshot 2024-05-23 at 13 56 11

**Comment by lucaguindani** [comment]
> > I don't think it's an issue. If you add a max-width (~310px) to the .line__group__title it should work. Maybe it should have different values depending on the screen size.
> 
> there will be this kind of problem, the "sub" content below will be hidden (because absolute position)
> 
> screenshot 2024-05-23 at 13 56 11

Correct me if I'm wrong, but I don't think it's possible to have such a long first label in the hierarchy ? For dates the longest would be the months, for texts the first label in the hierarchy is always a single alphabet letter and then the content of the selected field (no third hierarchical element).

**Comment by lucaguindani** [comment]
> * [ ]  [line-items-disposition](https://github.com/catima/catima/assets/1675064/81739203-38ba-478f-82f3-b7284f82eafe) items under the same hierarchy should be on the same side

Two or more items under the same hierarchy is now [breaking the component](https://github.com/catima/catima/assets/1675064/ac299635-9e69-4df5-8d26-d3fe8e2e4589)


> * [ ]  [line-items-margin](https://github.com/catima/catima/assets/1675064/b89a85d5-b3ad-4f19-8b40-ae399b92deb4) Reduce the bottom margin of the items

I don't see any changes. [The extra spacing](https://github.com/catima/catima/assets/1675064/1b32d611-f82e-45dc-b10d-c6f09283cbad) is still there on my local instance.

> * [ ]  [line-label-overlap](https://github.com/catima/catima/assets/1675064/0194f6e5-75f0-48ca-9d91-374d1e705f5e) Avoid overlap with long labels

We should have two lines max, then if the label is longer than that, we should have the text truncated & title added. Right now we have only one line (https://github.com/catima/catima/pull/549#issuecomment-2126945133, https://github.com/catima/catima/pull/549#issuecomment-2126984901)

@abstracts33d I am available if anything needs to be clarified.

**Comment by abstracts33d** [comment]
> ould have two lines max, then if the label is longer than that, we should have the text truncated & title added. Right now we have only o

Multi line titles cause this problem 
image

Margins seems pretty minimal on this test case (there is a min-height on the line__group to prevent title colliding) this is why exact  0 margin do not seems possible
image

**Comment by lucaguindani** [comment]
> Two or more items under the same hierarchy is now [breaking the component](https://github.com/catima/catima/assets/1675064/ac299635-9e69-4df5-8d26-d3fe8e2e4589)

@abstracts33d [still breaking](https://github.com/catima/catima/assets/1675064/cbd54504-d8ca-404b-bbc0-f98b32c6e3e0)

**Comment by lucaguindani** [comment]
> Margins seems pretty minimal on this test case (there is a min-height on the line__group to prevent title colliding) this is why exact 0 margin do not seems possible image

@abstracts33d Correct me if I'm wrong, but I don't see what could be the issue with the following.

```
.color-contrast-medium {
  margin-bottom: 0;
}
```

**Comment by lucaguindani** [comment]
> > Two or more items under the same hierarchy is now [breaking the component](https://github.com/catima/catima/assets/1675064/ac299635-9e69-4df5-8d26-d3fe8e2e4589)
> 
> ~~@abstracts33d [still breaking](https://github.com/catima/catima/assets/1675064/cbd54504-d8ca-404b-bbc0-f98b32c6e3e0)~~

I'm strange, now it's working... maybe a asset compilation issue. However, items under the same hierarchy are still [not on the same side](https://github.com/catima/catima/assets/1675064/68f20013-797a-4a7b-b370-dd47b680e4a3).

**Comment by lucaguindani** [comment]
> Multi line titles cause this problem image

✅

**Comment by abstracts33d** [comment]
> > Margins seems pretty minimal on this test case (there is a min-height on the line__group to prevent title colliding) this is why exact 0 margin do not seems possible image
> 
> @abstracts33d Correct me if I'm wrong, but I don't see what could be the issue with the following.
> 
> ```
> p.color-contrast-medium {
>   margin-bottom: 0;
> }
> ```

You re right it's working fine (we were not talking about the same paddings / margins)

**Comment by abstracts33d** [comment]
> > Multi line titles cause this problem image
> 
> @abstracts33d ✅

This screenshot is not working can you pls upload another one ? is this in order (relative to the  ✅ )

**Comment by abstracts33d** [comment]
> > > Two or more items under the same hierarchy is now [breaking the component](https://github.com/catima/catima/assets/1675064/ac299635-9e69-4df5-8d26-d3fe8e2e4589)
> > 
> > 
> > ~@abstracts33d [still breaking](https://github.com/catima/catima/assets/1675064/cbd54504-d8ca-404b-bbc0-f98b32c6e3e0)~
> 
> @abstracts33d Hummm strange, now it's working... maybe an asset compilation issue.
> 
> ! **However**, items under the same hierarchy are still [not on the same side](https://github.com/catima/catima/assets/1675064/68f20013-797a-4a7b-b370-dd47b680e4a3).

image

**Pull request merged**
