### PR TITLE
Upgrade to Rails 7.1

### PR DESCRIPTION
**Pull request by lucaguindani**

### CODE REVIEW

**Comment by daviserez** [comment]
lngtm

**Comment by lucaguindani** [comment]
! Check/update Redis envars in staging/production

#REDIS_HOST=your-redis-host.example.com
#REDIS_PORT=6379
#REDIS_DB=0

**Comment by lucaguindani** [comment]
! Tooltips not working anymore

Search for `"data-toggle" => "tooltip"`

**Comment by lucaguindani** [comment]
> ! Tooltips not working anymore
> 
> Search for `"data-toggle" => "tooltip"`

Should be solved by https://github.com/catima/catima/pull/533/commits/06d2b6fbd7ae709977bedc63065cb90e4c576fdb

**Comment by lucaguindani** [comment]
Deprecation warnings `Rails.application.secrets` are related to the **devise** gem, see pr below.

https://github.com/heartcombo/devise/pull/5634

Waiting for gem update to solve the issue and remove the warnings.

**Comment by lucaguindani** [comment]
Deprecation warning `Support for RSpec 2.X will be dropped in v3.0` is related to the **rswag** gem, see issue below.

https://github.com/rswag/rswag/issues/611

Should be solved by v3 of the gem ([not released yet](https://github.com/rswag/rswag/milestone/2)).

**Pull request merged**
